owner: pragma-ai # GitHub username
repo: upptime # GitHub repository name
sites: # List of endpoints to track
    - name: Pragma Dashboard
      url: https://app.pragma.ai
    - name: Pragma API
      url: https://api.pragma.ai/dashboard/api/user
      expectedStatusCodes:
          - 401
assignees: # Users to assign downtime issues (optional)
    - Araneline
    - liorshk
    - lckmain
    - sergey-galenko
status-website:
    publish: true
    baseUrl: /upptime
    favicon: https://raw.githubusercontent.com/pragma-ai/upptime/master/assets/favicon-32x32.png
    faviconSvg: https://raw.githubusercontent.com/pragma-ai/upptime/master/assets/logo.svg
    logoUrl: https://raw.githubusercontent.com/pragma-ai/upptime/master/assets/logo.svg
    name: Pragma Upptime
    introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
    introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
    links:
        - rel: shortcut icon
          href: https://raw.githubusercontent.com/pragma-ai/upptime/master/assets/favicon.ico
    navbar:
        - title: Status
          href: /$REPO
        - title: GitHub
          href: https://github.com/$OWNER/$REPO
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
